apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
spec:
  limits:
  - type: Container
    default:
      cpu: 1
      memory: 3Gi
    defaultRequest:
      cpu: 32m
      memory: 128Mi
